= Kaitai Struct: Python notes
:source-highlighter: coderay

## Requirements

<<ksy_reference#enums,Enums>> implementation in Python requires a enum support as described in https://www.python.org/dev/peps/pep-0435/[PEP-0435]. This support is available out of the box in standard libraries since Python v3.4, or since v2.4 using https://pypi.python.org/pypi/enum34[enum34] PyPi compatibility layer.

* On Debian / Ubuntu, this library can be installed with `sudo apt-get install python-enum34`
* Otherwise, one can use just `sudo pip install enum34`

## setuptools extension

https://setuptools.readthedocs.io/en/latest/[Setuptools] is the de-facto standard way of building and installing python packages. This library allows extension with https://setuptools.readthedocs.io/en/latest/setuptools.html#extending-and-reusing-setuptools[plugins]. https://github.com/KOLANICH have developed https://github.com/KOLANICH/kaitaiStructCompile.py[an extension to setuptools], allowing you to automate compilation of `*.ksy` files as the part of python module build process. The library provides a mostly declarative syntax to facilitate installation: you add a parameter `kaitai` to your `setup.py` where you enumerate files that you want compiled, output directory, compilation flags, and source code post-compilation transformations. Here are some examples: https://github.com/KOLANICH/NTMDTRead/blob/master/setup.py[1], https://github.com/KOLANICH/SpecprParser.py/blob/master/setup.py[2].

Here are https://github.com/KOLANICH/kaitaiStructCompile.py/blob/master/kaitaiStructCompile/config.schema.json[the docs] in JSON Schema format.

Please remember that this lib is VERY UNSTABLE and very likely to be improved in a way that changes API (but due to API simplicity it'd be easy to fix your code), but I guess it's much better to use this than to reinvent the wheel. https://github.com/KOLANICH/kaitaiStructCompile.py/issues[Contributions are welcome!]

Please note that this lib is NOT available on https://pypi.python.org[pypi] and if you want to install it automatically, you should add `git+https://github.com/KOLANICH/kaitaiStructCompile.py` into `dependency_links` in the config passed to `setuptools.setup`.
