= Kaitai Struct: Python notes
Kaitai Project
v0.9
:toc: left

[[overview]]
== Overview

[[ksc]]
=== Kaitai Struct compiler invocation

To generate Python modules, Kaitai Struct compiler should be invoked with
`-t python` option:

[source,shell]
kaitai-struct-compiler -t python my_spec.ksy

This normally generates `my_spec.py` parser module, which is compatible
with both Python 2 and 3.

TODO: document `--python-package`

[[add-runtime]]
=== Adding runtime library

Code generated by Kaitai Struct compiler will require additional runtime
library (https://pypi.org/project/kaitaistruct/[kaitaistruct at PyPi],
https://github.com/kaitai-io/kaitai_struct_python_runtime[sources at
GitHub]).

Runtime library API version must match compiler version that you're using
(i.e. if you use ksc v0.8, then you must use compatible v0.8 runtime).

[[add-runtime-release]]
==== Using release version

With stable version of Kaitai Struct compiler, one can use use following
methods:

* On Debian / Ubuntu, one can install it from apt repositories:

** For Python 2.x:
+
[source,shell]
sudo apt-get install python-kaitaistruct
+
Reference: https://packages.debian.org/buster/python-kaitaistruct[package info for Debian], https://packages.ubuntu.com/eoan/python-kaitaistruct[package info for Ubuntu]

** For Python 3.x:
+
[source,shell]
sudo apt-get install python3-kaitaistruct
+
Reference: https://packages.debian.org/buster/python3-kaitaistruct[package info for Debian], https://packages.ubuntu.com/eoan/python3-kaitaistruct[package info for Ubuntu]

* If your project is using *requirements.txt* to manage your
  dependencies, add the following line to it:
+
----
kaitaistruct
----
+
and then run `pip install -r requirements.txt` to update all your
dependencies.

* Otherwise, you can just install the package manually using *pip*
  (Python package manager):
+
[source,shell]
pip install kaitaistruct

[[add-runtime-snapshot]]
==== Using latest (snapshot) version

If you're using latest (unreleased AKA "unstable" AKA "snapshot") build
of Kaitai Struct compiler, that will require latest runtime libraries as
well:

* If your project is using *requirements.txt* to manage your
  dependencies, add the following line to it:
+
----
kaitaistruct @ git+https://github.com/kaitai-io/kaitai_struct_python_runtime.git
----
+
and then run `pip install -r requirements.txt` to update all your
dependencies.

* Otherwise, you can just install the package manually using *pip*
  (Python package manager):
+
[source,shell]
pip install --upgrade --pre git+https://github.com/kaitai-io/kaitai_struct_python_runtime.git

[[add-dependencies]]
=== Adding dependencies

<<ksy_reference#enums,Enums>> implementation in Python requires a enum
support as described in
https://www.python.org/dev/peps/pep-0435/[PEP-0435]. This support is
available out of the box in standard libraries since Python v3.4, or
since v2.4 using https://pypi.org/project/enum34/[enum34] PyPi
compatibility layer.

* On Debian / Ubuntu, this library can be installed with `sudo apt-get
  install python-enum34`
* Otherwise, one can use just `sudo pip install enum34`

[[automation]]
=== Automation of compilation process

https://setuptools.readthedocs.io/en/latest/[Setuptools] is the de-facto
standard way of building and installing python packages. This library
allows extension with
https://setuptools.readthedocs.io/en/latest/setuptools.html#extending-and-reusing-setuptools[plugins].
https://github.com/KOLANICH have developed
https://github.com/kaitaiStructCompile/kaitaiStructCompile.py[an extension to
setuptools], allowing you to automate compilation of `*.ksy` files as the
part of python module build process. The library provides a mostly
declarative syntax to facilitate installation: you add a parameter
`kaitai` to your `setup.py` where you enumerate files that you want
compiled, output directory, compilation flags, and source code
post-compilation transformations. Here are some examples:
https://github.com/KOLANICH/NTMDTRead/blob/master/setup.py[1],
https://github.com/KOLANICH/SpecprParser.py/blob/master/setup.py[2].

Here are
https://github.com/KOLANICH/kaitaiStructCompile.py/blob/master/kaitaiStructCompile/config.schema.json[the
docs] in JSON Schema format.

Please remember that this lib is VERY UNSTABLE and very likely to be
improved in a way that changes API (but due to API simplicity it'd be
easy to fix your code), but I guess it's much better to use this than to
reinvent the wheel.
https://github.com/kaitaiStructCompile/kaitaiStructCompile.py/issues[Contributions
are welcome!]

Please note that this lib is NOT available on
https://pypi.org/[pypi] and if you want to install it
automatically, you should add
`git+https://github.com/KOLANICH/kaitaiStructCompile.py` into
`dependency_links` in the config passed to `setuptools.setup`.
