#!/usr/bin/env ruby
# coding: utf-8

require 'fileutils'

if ARGV.size != 2
  puts "Usage: postprocess-html <src-file> <dst-file>"
  exit 1
end

src, dst = ARGV

doc = File.read(src)

navbar_html = File.read("tmpl/navbar.html")
footer_html = File.read("tmpl/footer.html")
header_html = File.read("tmpl/header.html")

doc.gsub!(/<div id="header">/, navbar_html + "<div id=\"header\">")
doc.gsub!(/<div id="footer">.*$/m, footer_html)
doc.gsub!(/<\/title>/, "</title>\n" + header_html.rstrip)

FileUtils::mkdir_p(File.dirname(dst))
File.write(dst, doc)
